# Generated by Django 5.0.2 on 2024-03-15 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artist_options_alter_artist_managers_and_more'),
        ('musics', '0013_alter_music_class_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music_class',
            old_name='Genres',
            new_name='genres',
        ),
        migrations.AlterField(
            model_name='music_class',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='artists.artist'),
        ),
    ]
